In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import random

In [4]:
from datetime import datetime, timedelta

In [5]:
random.seed(42)

In [6]:
np.random.seed(42)

In [7]:
n_publicaciones = 1000000

In [8]:
influencers = [
    "ana_viaja",
    "cancun_life",
    "playas_mex",
    "travel_life",
    "vida_en_mar",
    "turismo_cancun",
    "vibras_nuevas",
    "band-life"
]

tipos_post = [
    "foto",
    "reel",
    "historia",
    "video"
]

In [9]:
dataset = pd.DataFrame({
    
    "influencer": [
        random.choice(influencers)
        for _ in range(n_publicaciones)
    ],
    
    "likes": [
        random.randint(100, 50000)
        for _ in range(n_publicaciones)
    ],
    
    "comentarios": [
        random.randint(0, 5000)
        for _ in range(n_publicaciones)
    ],
    
    "fecha": [
        datetime(2025,1,1) + timedelta(days=random.randint(0,365))
        for _ in range(n_publicaciones)
    ],
    
    "tipo_post": [
        random.choice(tipos_post)
        for _ in range(n_publicaciones)
    ]
})

In [10]:
dataset.head()

    influencer  likes  comentarios      fecha tipo_post
0  cancun_life  36506         4212 2025-09-08     video
1    ana_viaja   1293         2614 2025-12-27     video
2  vida_en_mar  20478         4785 2025-02-05      reel
3  travel_life  34225          525 2025-07-04      foto
4  travel_life  24897         3838 2025-04-28      reel

In [11]:
dataset.shape

(1000000, 5)

In [12]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 5 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   influencer   1000000 non-null  object
 1   likes        1000000 non-null  int64
 2   comentarios  1000000 non-null  int64
 3   fecha        1000000 non-null  datetime64[ns]
 4   tipo_post    1000000 non-null  object
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 38.1+ MB

In [13]:
dataset.describe()

                likes     comentarios                          fecha
count  1000000.000000  1000000.000000                        1000000
mean     25042.815864     2498.366509  2025-07-02 10:11:27.081600512
min        100.000000        0.000000            2025-01-01 00:00:00
25%      12591.000000     1247.000000            2025-04-02 00:00:00
50%      25030.000000     2497.500000            2025-07-02 00:00:00
75%      37524.000000     3751.000000            2025-10-02 00:00:00
max      50000.000000     5000.000000            2026-01-01 00:00:00
std      14400.763826     1444.887981                            NaN

In [14]:
dataset["likes"].mean()

np.float64(25042.815864)

In [15]:
dataset["comentarios"].mean()

np.float64(2498.366509)

In [16]:
dataset["tipo_post"].value_counts()

tipo_post
foto        250482
reel        250246
historia    250017
video       249255
Name: count, dtype: int64

In [17]:
dataset["influencer"].value_counts()

influencer
vida_en_mar       125521
cancun_life       125404
turismo_cancun    125362
ana_viaja         125233
band-life         124846
playas_mex        124714
vibras_nuevas     124692
travel_life       124228
Name: count, dtype: int64

In [18]:
dataset.sort_values(by="likes", ascending=False).head(10)

           influencer  likes  comentarios      fecha tipo_post
875097      ana_viaja  50000         2614 2025-08-04      reel
95516      playas_mex  50000         1204 2025-02-28  historia
875225    cancun_life  50000          697 2025-07-30      reel
598979  vibras_nuevas  50000         4561 2025-02-27     video
245887     playas_mex  50000         1020 2025-12-20      reel
809724    vida_en_mar  50000         2339 2025-08-03     video
656400    vida_en_mar  50000          171 2025-01-18  historia
40403      playas_mex  50000         1765 2025-05-03  historia
803618    vida_en_mar  50000           96 2025-12-07      reel
422107    travel_life  50000         2461 2025-10-08      foto